language: ruby
rvm:
- 3.0.0
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - main
deploy:
  provider: s3
  access_key_id: AKIAVHZ4DGU55IXXGYXX
  secret_access_key:
    secure: TtZKVLICk5x2vAGDgxYwmrg/1846QiGmVFvMWSeJocufDV0BZqJLi4kUU5HJ46popIBlfV9awzNIe9LqZrVGActYeB/pdQSBEL0sLvR+mtnwMjejQxhxhifkAnt7ptL1T2gH2WZzHZ97lZtoRCPnKWt+Zf08c4/NNyQZDG0uaUOhwyebtgmMNff5XzbQOw3lsWteQCf17dDyO8njU6dcJybMLX8NbD1MEbaATwbseLf2h3xLq7xo5blaByaIVvrexfpaTvedh4jlMUsFGaMEkZNcDuyMfjh7K1KoIFnRu54QUWJC8DQ1v+CR0GPzQahKyEyu1J9JtnG77JC5Kr1JK8b4/fnefIeGSVZ9eS9oNdyEmUtCVY53l7aDKkKyO8+8DPUfx5yEA7gk1MdUqIGte6TmuHqbWI9C7E9FL51q3/QLJrsvrs4xv4J1ipmroI6dZEdWIHaK8P0HT+zaUq+Y6UfJgTkaegYyUZk00S3ggBf4hXwab5fJHCigx9NCvwmmUiUYMWgN8z+BwCo8hg+MJATxoAIikkQhtmubRLOcu5QnL9ohA4snreAb+ed0G+l9fFz95erQwcl5b4beqoGpIhJ9VnpUDCfF6zeYuC7KcxUfzPkNImfsNRpHiM9lgn3YK4dy4NLfv6lAIGYbsbkdQ2BsxLCNXSBeSDMn4BXBhS0=
  bucket: www.djabstraction.com
  local-dir: _site
  acl: public_read
  on:
    repo: devoctomy/djabstraction.com
    branch: main
  skip_cleanup: 'true'
  region: eu-west-1
