title:              DJ Abstraction
email:
description:        House & Trance Mixes
author:             DJ Abstraction
baseurl:            ""
url:                "http://www.djabstraction.com"

twitter_username:
github_username:
facebook_username:
instagram_username: djabstraction
linkedin_username:

google_analytics:   G-1P8T5L4LH8

markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
