title:              DJ Abstraction
email:              djabstraction@npsoftware.co.uk
description:        House & Trance Mixes
author:             DJ Abstraction
baseurl:            ""
url:                "http://www.djabstraction.com"

twitter_username:    djabstraction
github_username:     nickdevoctomy
facebook_username:   djabstraction
instagram_username:  djabstraction
linkedin_username:
spotify_userid:      1112143992 
soundcloud_username: nick-pateman-685424405

podcast_url: http://www.djabstraction.com/feed/podcast
podcast_album_art: /img/podcast/podcast.jpg
podcast_title: DJ Abstraction's Mix Podcast
podcast_owner: Nick Pateman
podcast_email: djabstraction@npsoftware.co.uk
podcast_category: Music
podcast_subcategory_one: Mixes
podcast_subcategory_two: Dance
podcast_explicit: "no"
podcast_author: Nick Pateman
podcast_description: House and Trance Mixes
podcast_summary: House and Trance Mixes

google_analytics:   G-1P8T5L4LH8
enable_comments:    false

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

markdown:           kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
