title:              DJ Abstraction
email:              nick@djabstraction.com
description:        House & Trance Mixes by DJ Abstraction.
author:             Nick Pateman
baseurl:            ""
url:                "https://www.djabstraction.com"

# Social Profiles
twitter_username:   bob
github_username:    bob
facebook_username:  bob
instagram_username: bob
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
