title:              DJ Abstraction
email:              djabstraction@npsoftware.co.uk
description:        House & Trance Mixes
author:             DJ Abstraction
baseurl:            ""
url:                "https://www.djabstraction.com"

instagram_username:  djabstraction
linkedin_username:
spotify_userid:      firkinfedup

podcast_url: https://www.djabstraction.com/feed/podcast.xml
podcast_album_art: /img/podcast/podcast.jpg
podcast_title: DJ Abstraction's Warmup Sessions
podcast_shorttitle: Warmup Sessions
podcast_owner: Nick Pateman
podcast_email: djabstraction@npsoftware.co.uk
podcast_primarycategory: Music
podcast_explicit: False
podcast_author: DJ Abstraction
podcast_description: House and Trance Mixes by DJ Abstraction. Mixed and recorded live with the best selection of House and Trance.
podcast_language: en-GB
podcast_copyright: Copyright 2006 - 2024 DJ Abstraction

google_tagmanager:  GTM-NVQP42Q

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

markdown:           kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
